<?php if ($block->getCarData()): ?>
<figure class="car-figure">
 <img src="" alt="" />
 <figcaption><?= $block->getCarData()['car_make'] ?> | <?= $block->getCarData()['car_model'] ?></figcaption>
</figure>
<?php else: ?>
<p><?= __('No car profile data found.'); ?></p>
<?php endif; ?>

<form action="<?= $block->getUrl('carprofile/index/post'); ?>" method="post" data-mage-init='{"validation": {}}'>

 <input type="hidden" name="form_key" value="<?= $block->getFormKey() ?>" />

 <fieldset class="fieldset car">
 
  <div class="field car_make required">
   <label class="label" for="car_make">
    <span><?= __('Car Make') ?></span>
   </label>
   <div class="control">
    <select name="car_make" data-validate='{"required":true}'>
     <option value=""><?= __('Select Item') ?></option>
    </select>
   </div>
  </div>

  <div class="field car_model required">
   <label class="label" for="car_model">
    <span><?= __('Car Model') ?></span>
   </label>
   <div class="control">
    <select name="car_model" data-validate='{"required":true}'>
     <option value=""><?= __('Select Item') ?></option>
    </select>
   </div>
  </div>

  <div class="actions-toolbar">
   <div class="primary">
    <button type="submit" class="action save primary" title="Save Car">
     <span><?= __('Save Cars') ?></span>
    </button>
   </div>
  </div>

 </fieldset>

</form>

<script>

 require([
  'jquery'
 ], function ($) {
    
  'use strict';

  var $endpoint = 'https://exam.razoyo.com/api/cars';

  var getCarMake = function(url) {
   $.ajax({
    url: url,
    method: 'GET',
    beforeSend: function( xhr ) {
      $('body').trigger('processStart');
    },
    success: function(res) {
     let $data = res.makes;
     let $items = $data.map(function(item, key) {
      return `
       <option value="${item}">${item}</option>
      `
     }).join('');
     $('select[name="car_make"]')
      .append($items)
      .on('change',function(){
       getCarModel(`${$endpoint}?make=${$(this).val()}`);
     });
     $('body').trigger('processStop');
    },
    error: function(xhr, status, error) {
     console.error('Error:', error);
    }
   });
  }

  var getCarModel = function(url) {
   $.ajax({
    url: url,
    method: 'GET',
    success: function(res) {
     let $data = res.cars;
     let $items = $data.map(function(item, key) {
      return `
       <option value="${item.model}" data-id="${item.id}" data-year="${item.year}">${item.model}</option>
      `
     }).join('');
     $('select[name="car_model"]').children('option:not(:first)').remove();
     $('select[name="car_model"]').append($items);
    },
    error: function(xhr, status, error) {
     console.error('Error:', error);
    }
   });
  }

  getCarMake($endpoint);

});

</script>
