<?php

 if ($block->getCarData()):

  $id = $block->getCarData()['car_id'];
  $make = $block->getCarData()['car_make'];
  $model = $block->getCarData()['car_model'];
  $year = $block->getCarData()['car_year'];
  $mpg = $block->getCarData()['car_mpg'];
  $price = $block->formatPrice($block->getCarData()['car_price']);
  $seats = $block->getCarData()['car_seats'];
  $image = $block->getCarData()['car_image'];
?>
<div id="car-<?= $id ?>" class="car-data">
 <figure class="car-figure">
    <img class="car-image" src="<?= $image ?>" alt="<?= $make . " | " . $model ?>" />
    <figcaption class="car-caption">
     <span class="car-name"><?= $make .' '. $model .' '. $year ?></span>
     <span class="car-price"><?= $price ?></span>
    </figcaption>
 </figure>
 <div class="car-description">
  <p><?= $make .' '. $model .' '. $year . ' is a ' . $seats . ' seater car rated at ' . $mpg . ' MPG.' ?> <p>
 </div>
</div>
<?php else: ?>
  <div class="car-data">
   <figure class="car-figure">
    <img class="car-image" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Vw8AAoEBfymqrywAAAAASUVORK5CYII=">
    <figcaption class="car-caption">
     <span class="car-name"><?= __('No car profile data found.'); ?></span>
     <span class="car-price"></span>
    </figcaption>
   </figure>
   <div class="car-description"></div>
  </div>
<?php endif; ?>

<form id="car-profile-form" action="<?= $block->getUrl('carprofile/index/post'); ?>" method="post" data-mage-init='{"validation": {}}'>
    <input type="hidden" name="form_key" value="<?= $block->getFormKey() ?>" />
    <fieldset class="fieldset car">
        <input type="hidden" name="car_id" value="" />
        <input type="hidden" name="car_year" value="" />
        <input type="hidden" name="car_mpg" value="" />
        <input type="hidden" name="car_price" value="" />
        <input type="hidden" name="car_seats" value="" />
        <input type="hidden" name="car_image" value="" />
        <div class="field car_make required">
            <label class="label" for="car_make">
                <span><?= __('Car Make') ?></span>
            </label>
            <div class="control">
                <select name="car_make" data-validate='{"required":true}'>
                    <option value=""><?= __('Select Item') ?></option>
                </select>
            </div>
        </div>
        <div class="field car_model required">
            <label class="label" for="car_model">
                <span><?= __('Car Model') ?></span>
            </label>
            <div class="control">
                <select name="car_model" data-validate='{"required":true}'>
                    <option value=""><?= __('Select Item') ?></option>
                </select>
            </div>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action save primary" title="Save Car">
                    <span><?= __('Save Cars') ?></span>
                </button>
            </div>
        </div>
    </fieldset>
</form>

<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/alert',
        'mage/validation'
    ], function ($, alert) {
        'use strict';

        var $endpoint = 'https://exam.razoyo.com/api/cars';

        var getCarMake = function(url) {
            $.ajax({
                url: url,
                method: 'GET',
                beforeSend: function() {
                    $('body').trigger('processStart');
                },
                success: function(response, textStatus, jqXHR) {
                    let $data = response.makes;
                    let $field = $('select[name="car_make"]');
                    let $items = $data.map(function(item) {
                        return `<option value="${item}">${item}</option>`;
                    }).join('');
                    $field.append($items)
                        .on('change', function() {
                            getCarModel(`${$endpoint}?make=${$(this).val()}`);
                        });
                    $('body').trigger('processStop');
                },
                error: function(xhr, status, error) {
                    $('body').trigger('processStop');
                    console.error('Error:', error);
                }
            });
        };

        var getCarModel = function(url) {
            $.ajax({
                url: url,
                method: 'GET',
                success: function(response, textStatus, jqXHR) {
                    let $data = response.cars;
                    let $field = $('select[name="car_model"]');
                    let $items = $data.map(function(item) {
                        return `<option value="${item.model}" data-id="${item.id}">${item.model}</option>`;
                    }).join('');
                    $field.children('option:not(:first)').remove();
                    $field.append($items);
                    $field.off().on('change', function() {
                        getCarData(
                         $endpoint,
                         $(this).find(':selected').data('id'),
                         jqXHR.getResponseHeader('Your-Token')
                        );
                    });
                },
                error: function(xhr, status, error) {
                    console.error('Error:', error);
                }
            });
        };

        var getCarData = function(url, id, token) {
            $.ajax({
                url: `${url + '/' + id}`,
                method: 'GET',
                headers: {"Authorization": "Bearer " + token},
                success: function(response, textStatus, jqXHR) {
                    let $car = response.car;
                    $('input[name="car_id"]').val($car.id);
                    $('input[name="car_year"]').val($car.year);
                    $('input[name="car_mpg"]').val($car.mpg);
                    $('input[name="car_price"]').val($car.price);
                    $('input[name="car_seats"]').val($car.seats);
                    $('input[name="car_image"]').val($car.image);
                },
                error: function(xhr, status, error) {
                    console.error('Error:', error);
                }
            });
        };

        var submitForm = function() {
    $('#car-profile-form').on('submit', function(event) {
        event.preventDefault();
        var form = $(this);

        if (!form.validation('isValid')) {
            return;
        }

        var formKey = $('input[name="form_key"]').val();

        $.ajax({
            url: form.attr('action'),
            method: 'POST',
            dataType: 'json',
            data: form.serialize() + '&form_key=' + formKey,
            beforeSend: function() {
                $('body').trigger('processStart');
            },
            success: function(response) {
                $('body').trigger('processStop');
                if (response.success) {
                    console.log(response);
                    let $carMake = response.car_make;
                    let $carModel = response.car_model;
                    let $carYear = response.car_year;
                    let $carPrice = response.car_price;
                    let $carSeats = response.car_seats;
                    let $carMpg = response.car_mpg;
                    let $carImage = response.car_image;
                    alert({
                        content: response.message
                    });
                    $('.car-figure .car-image').attr('src', $carImage);
                    $('.car-figure .car-name').text(
                        `${$carMake} ${$carModel} ${$carYear}`
                    );
                    // Display price with the currency symbol
                    $('.car-figure .car-price').text(`${$carPrice}`);
                    $('.car-description').html(`
                        <p>${$carMake} ${$carModel} ${$carYear} is a ${$carSeats} seater car rated at ${$carMpg} MPG.</p>
                    `);
                    
                } else {
                    alert({
                        content: response.message || 'An error occurred while saving the car profile.'
                    });
                }
            },
            error: function(xhr, status, error) {
                $('body').trigger('processStop');
                alert({
                    content: 'Error: ' + error
                });
            }
        });
    });
}


        getCarMake($endpoint);
        submitForm();

    });
</script>
